name: Markdownlint Action
on: push

jobs:
  build:
    name: Markdownlint
    runs-on: ubuntu-latest
    steps:
      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v2.0.0
        with:
          files: .
          config_file: ".markdownlint.yaml"
